### ISSUE TITLE
Question regarding this commit

### ISSUE THREAD

**Issue by Urmi10799** [Kerwin1202/chatgpt-web#149]
[feat: 允许查看历史响应结果](https://github.com/Kerwin1202/chatgpt-web/commit/1a392721bd0d39fcb7e6998b4cd3b05f9a2a1066)

In your recent commit, I can't see any changes? can you kindly please explain where this take effect. where to viewing historical response results? I see a group button is implemented but can't access it

**Comment by Kerwin1202** [comment]
Like this. Only after regenerate response, it will be shown. The function is to display the previous response.

<img width="294" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/a0cf5c9a-7ba4-4bb3-b5c4-db3ec759cbef">
<img width="492" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/fa316007-a0ba-486b-ba9e-ab1f5bf3136b">

**Comment by Urmi10799** [comment]
> Like this. Only after regenerate response, it will be shown. The function is to display the previous response.
> 
> <img alt="image" width="294" src="https://user-images.githubusercontent.com/16319833/239749059-a0cf5c9a-7ba4-4bb3-b5c4-db3ec759cbef.png"> <img alt="image" width="492" src="https://user-images.githubusercontent.com/16319833/239749100-fa316007-a0ba-486b-ba9e-ab1f5bf3136b.png">

thank you Kerwin. I have another question regarding this commit: [chore: Each dialog context is independent](https://github.com/Kerwin1202/chatgpt-web/commit/82888b9d4334300f15365534a804652915976160)

Can you please explain how this works: Each dialog context is independent. I mean a working principle.

**Comment by Kerwin1202** [comment]
If I need a certain chat room just to provide me with the function of regular expressions, every time I enter, for example, email, it will only return the regular expression of email. Or the function of translation, I only need to input the original text, and he will output the translated content for me. At this time, there is actually no need for context association, because this has already been set in the prompt. So closing the context at this time can reduce the consumption of tokens. Adding this commit is convenient for different chat rooms to switch settings, so save this setting for a certain chat room

**Comment by Kerwin1202** [comment]
Each room can set its own status, without forgetting when switching rooms.  
Most of the time, regular expressions and translations do not require context and should be turned off. This avoids frequent switching and is easy to forget. 
The purpose is to reduce the consumption of tokens.

<img width="365" alt="image" src="https://github.com/Kerwin1202/chatgpt-web/assets/16319833/08a2d453-6e9a-4eb0-9064-023709e5ccc6">
